****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBSD0080																																
0120																																
754																																
                40																																
%_HEADER																																
SAPMZBSD0080                            0120M0120     17 93192 37  0  0 27122  0G E                              20241105114454																																
%_DESCRIPTION																																
120																																
%_FIELDS																																
		CHAR	 88	00	00	00	30	00	  2	  7		  0	  0	  0		 16	R				  0	  0	101									
ZTBMM1020-PLTCODE	2	CHAR	 20	30	00	00	30	00	  4	 10		  0	  0	  0		  0					  0	  0								플랜트 코드	                                                                                                                                                                                                                                                        X	
ZTBMM1020-PLTCODE	C	CHAR	 10	A0	00	80	30	08	  4	 31		  0	  0	  0		  0					 20	  0								__________	X                                      00	
ZTBMM1020-PLTNAME	2	CHAR	 20	30	00	00	30	00	  6	 10		  0	  0	  0		  0					  0	  0								플랜트 명	                                                                                                                                                                                                                                                        X	
ZTBMM1020-PLTNAME	C	CHAR	 10	A0	00	A0	00	00	  6	 31		  0	  0	  0		  0					 20	  0								__________	                                       00	
ZTBMM1020-PLTADNR	2	CHAR	 20	30	00	00	30	00	  8	 10		  0	  0	  0		  0					  0	  0								플랜트 주소	                                                                                                                                                                                                                                                        X	
ZTBMM1020-PLTADNR	C	CHAR	 50	A0	00	A0	00	00	  8	 31		  0	  0	  0		  0					100	  0								__________________________________________________	                                       00	
ZTBMM1020-EMPID	2	CHAR	 20	30	00	00	30	00	 10	 10		  0	  0	  0		  0					  0	  0								사원ID	                                                                                                                                                                                                                                                        X	
ZTBMM1020-EMPID	C	CHAR	 15	A0	00	80	30	00	 10	 31		  0	  0	  0		  0					 30	  0								_______________	                                       00	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE CLEAR_OK_CODE.																																
 MODULE STATUS_0120.																																
 MODULE SET_FIELD.																																
																																
PROCESS AFTER INPUT.																																
 MODULE EXIT_0120 AT EXIT-COMMAND.																																
 MODULE USER_COMMAND_0120.																																
