  "인포레코드 번호
<font color ="#0000FF">*  SELECT-OPTIONS TABLE CREATE</font>
  IF ZTBMM0070-INFNUM IS NOT INITIAL.
    RS_INFNUM-SIGN = 'I'.
    RS_INFNUM-OPTION = 'EQ'.
    RS_INFNUM-LOW = ZTBMM0070-INFNUM.
    APPEND RS_INFNUM TO RT_INFNUM.
  ENDIF.

  " 거래처 코드
  IF ZTBMM0070-BPCODE IS NOT INITIAL.
    RS_BPCODE-SIGN = 'I'.
    RS_BPCODE-OPTION = 'EQ'.
    RS_BPCODE-LOW = ZTBMM0070-BPCODE.
    APPEND RS_BPCODE TO RT_BPCODE.
  ENDIF.

  "계약시작일
  IF ZTBMM0070-DATSR IS NOT INITIAL.
    RS_DATSR-SIGN  = 'I'.
    RS_DATSR-OPTION = 'EQ'.
    RS_DATSR-LOW = ZTBMM0070-DATSR.
    APPEND RS_DATSR TO RT_DATSR.
  ENDIF.

  "계약종료일
  IF ZTBMM0070-DATEN IS NOT INITIAL.
    RS_DATEN-SIGN = 'I'.
    RS_DATEN-OPTION = 'EQ'.
    RS_DATEN-LOW = ZTBMM0070-DATEN.
    APPEND RS_DATEN TO RT_DATEN.
  ENDIF.

  "GET DATA
  SELECT *
    FROM ZTBMM0070
    INTO CORRESPONDING FIELDS OF TABLE GT_ZTBMM0070
    WHERE INFNUM IN RT_INFNUM
    AND BPCODE IN RT_BPCODE
    AND DATSR IN  RT_DATSR
    AND DATEN IN  RT_DATEN.

  "BP MASTER GET DATA

  IF ZTBSD1050-BPCODE IS NOT INITIAL.
    RS_BPCODE_SD-SIGN = 'I'.
    RS_BPCODE_SD-OPTION = 'EQ'.
    RS_BPCODE_SD-LOW = ZTBSD1050-BPCODE.
    APPEND RS_BPCODE_SD TO RT_BPCODE_SD.
  ENDIF.

  SELECT *
    FROM ZTBSD1050
    INTO TABLE GT_ZTBSD1050
    WHERE BPCODE IN RT_BPCODE_SD.
<font color ="#0000FF">*  IF ZTBSD1050-BPTCODE IS NOT INITIAL.</font>
<font color ="#0000FF">*    RS_BPNUM-SIGN = 'I'.</font>
<font color ="#0000FF">*    RS_BPNUM-OPTION = 'EQ'.</font>
<font color ="#0000FF">*    RS_BPNUM-LOW = ZTBSD1050-BPCODE.</font>
<font color ="#0000FF">*    APPEND RS_BPNUM_SD TO RT_BPNUM.</font>
<font color ="#0000FF">*  ENDIF.</font>



ENDFORM.



