****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZBRMM0020																																
0110																																
754																																
                40																																
%_HEADER																																
ZBRMM0020                               0110I0110      0  0192 37  0  0 27120  0G E                              20241212154100																																
%_DESCRIPTION																																
110																																
%_FIELDS																																
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0110.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0110.																																
